### ISSUE TITLE
Bug with fitting

### ISSUE THREAD

**Issue by mailund** [mailund/admixture_graph#13]
@KalleLeppala, when I run this code on the baboon data I get an error in the fitting code. Some months ago I could fit the graph but apparently not any longer. Do you have any idea what is going on?

``` r
leaves <- c("rheMac2","P.cynocephalus",  "P.ursinus", "P.kindae", "P.hamadryas", "P.anubis", "P.papio")
inner_nodes <- c("R", "x", "y", "z", "w", "anc.kindae", "anc.ursinus", "anc.hamadryas", "anc.anubis", "anc.papio")

edges <- parent_edges(c(
  edge("rheMac2", "R"),
  edge("x", "R"),
  edge("y", "x"),
  edge("z", "w"),edge("w", "x"),
  edge("P.kindae", "anc.kindae"), 
  admixture_edge("anc.kindae", "anc.ursinus", "w"), edge("anc.ursinus", "y"),
  edge("P.cynocephalus", "y"), 
  edge("P.ursinus", "anc.ursinus"), 
  edge("P.hamadryas", "anc.hamadryas"), edge("anc.hamadryas", "z"),
  edge("P.papio", "anc.papio"), edge("anc.papio", "z"),
  edge("P.anubis", "anc.anubis"),
  admixture_edge("anc.anubis", "anc.hamadryas", "anc.papio")
))
admixtures <- admixture_proportions(c(
  admix_props("anc.kindae", "anc.ursinus", "w", "a"),
  admix_props("anc.anubis", "anc.hamadryas", "anc.papio", "b")
))

kindae_admixed_graph_u3_anubis_papio_hamadryas <- agraph(leaves, inner_nodes, edges, admixtures)
plot(kindae_admixed_graph_u3_anubis_papio_hamadryas, show_admixture_labels = TRUE)

posf4 %>% filter_on_leaves(kindae_admixed_graph_u3_anubis_papio_hamadryas) %>%
  fit_graph(kindae_admixed_graph_u3_anubis_papio_hamadryas, options) -> fit_kindae_admixed_graph_u3_anubis_papio_hamadryas
```

**Comment by KalleLeppala** [comment]
Hi!

The problem is the word "options" in your code. Take a look at the syntax
of fit_graph(): the third parameter is point, which is used to fix or bound
some of the admixture proportions. If you want to feed something to
nelder_mead(), then use the sixth parameter, optimisation_options. So omit
"options" or replace it with "optimisation_options = options". I guess I
should have added my new parameters to the end, but I didn't and it's too
late now, sorry about that.

However, there appears to be a bug: after running fit_graph() the program
reports that none of the admixture variables is properly fitted, while
closer inspection reveals that in fact a is fitted and b is unnecessary.
The program chooses between three initial reports: nothing, something not
fitted, and nothing fitted. (In this case we expect the second report but
it gives the third.) I'll take a look on why the initial reporting is
malfunctioning.

I added a few more comments about the appnote. It's a good piece by the
way, especially appealing is how the toy example matches with the paper
about polar bears being admixed instead of ABC:s.

About the number of detectable admixture events: The case of three
populations was simple, I'll present it as my breakfast talk on Wednesday.
I can send you the slides or you can attend or I can explain it with
details face to face. Didn't have much time for generalization yet... looks
like there's a couple of issues generally more messy than in the case of
three populations, so it's not (yet) a peace of cake. Hopefully I can at
least take a couple of steps like four and five populations if not the full
thing.

-Kalle

**Comment by mailund** [comment]
You are right. I didn't notice the changes to the function.
