### ISSUE TITLE
Fitting graph, "Something went wrong, trying again."

### ISSUE THREAD

**Issue by grafau** [mailund/admixture_graph#17]
Hi Thomas,

I started using your R package; thanks for making admixture easier.

Sadly, when I try fitting graph to my f4 data I get a print: 
"Something went wrong, trying again." 
and I have no idea what's wrong. It prints it tens of times to conclude with error: 
"Error: C stack usage  7969328 is too close to the limit".

For example, I am using your graph and replace leaf names
```
  temp <- vector_to_graph(graphs_5_1[9, ])
  new_names <- list(B = "OUT", A = "EU1650", D = "AN1950", C = "CH1850", E = "EU1750")
  temp <- rename_nodes(temp, new_names) 
```

And then try following F4s

```
     W      X      Y      Z       D Z.value
1  OUT CH1850 AN1950 EU1650  0.0053   0.485
2  OUT CH1850 AN1950 EU1750  0.0987  11.552
3  OUT CH1850 AN1950 EU1850  0.0816   9.945
4  OUT CH1850 AN1950 EU1950  0.0359   4.395
5  OUT CH1850 AN1950 CH1950  0.0321   2.732
6  OUT CH1850 AN1950  Admix -0.0062  -0.697
7  OUT CH1850 EU1650 AN1950 -0.0053  -0.485
8  OUT CH1850 EU1650 EU1750  0.1057   9.860
9  OUT CH1850 EU1650 EU1850  0.0849   8.794
10 OUT CH1850 EU1650 EU1950  0.0314   2.801
11 OUT CH1850 EU1650 CH1950  0.0287   2.123
12 OUT CH1850 EU1650  Admix -0.0149  -1.260
```
To fit

`f4fit  <- fit_graph(f4ex, temp)`

I don't know what am I missing, any pointers are welcome.

**Comment by KalleLeppala** [comment]
Hi,

the problem is that EU1850 is not a leaf in the graph. The data can be
filtered using filter_on_leaves(), and it should probably be made the
default behavior. Sorry for not giving better error reports, the "something
went wrong..." is there in case of numerical issues that sometimes occur in
Nelder-Mead, but when you get it many times there is some actual problem
(this is probably most typical).

Kalle

**Comment by grafau** [comment]
Oh, I see, thank you, it works now!
